### PR TITLE
Last reorganized timestamp and access bits support

### PR DESCRIPTION
**Pull request by msuhanov**
1. REGFBlock: add the reorganized_timestamp() method.
2. NKRecord: add the access_bits() method.

### CODE REVIEW

**Comment by NiKiZe** [comment]
Nice! Any chance we can get tests added for these as well?

**Comment by msuhanov** [comment]
I can upload sample hive files here (attach them to the message) or include them in the pull request. Do we need a script to run against the samples?

**Comment by EricZimmerman** [comment]
if its at all possible, i would recommend using the hives i have in my Registry project so people can test against a common set of hives.

**Comment by NiKiZe** [comment]
There was some pytest style tests merged in #58 
But if there is anything else available.

with pytest (and six) installed it easy to run py.test in base directory and it will run test scripts in the project. Currently it seems we have a few non tests detected as tests which fails.

If we can add more testscripts to test other hives that is of-course good, but IMHO it is first and foremost important that all new code gets tests added.

**Comment by williballenthin** [comment]
code looks good, thanks! i'd definitely appreciate adding a few tests to demonstrate that the data expected is the data actually extracted. also, so we can identify regressions in the future. if there's any concerns there, let me know.

**Comment by williballenthin** [comment]
i've learned to configure travis during the FLOSS project, and now i can't believe i hadn't been using it. definitely want to set up automated testing for this project sometime in the near future.

**Comment by msuhanov** [comment]
I have added the test case based on the small hive used in Unicode tests (it was mounted and unmounted on a Windows 8.1 machine).

**Comment by williballenthin** [comment]
looks great, thanks!

**Pull request merged**
