### PR TITLE
Add MANIFEST.in

### LINKED ISSUE #95: Add docs to release
Please add the CHANGELOG.TXT, CONTRIBUTORS.TXT, LICENSE.TXT and the README.MD file to the release.

Thanks

### PR DESCRIPTION
**Pull request by fabaff**
Include documentation files as this is needed for a lot of distribution.

Fixes #95

### CODE REVIEW

**Comment by williballenthin** [comment]
thanks!

**Comment by fabaff** [comment]
Could you please publish a new release? Thanks

I need those files for the Fedora RPM package.

**Comment by williballenthin** [comment]
done

**Comment by fabaff** [comment]
Thank you

**Pull request merged**
