### PR TITLE
Fixed RegFileTime parsing

### PR DESCRIPTION
**Pull request by woanware**
Was using an old copy of python-registry whilst I worked on a project (https://github.com/woanware/usbdeviceforensics), then updated  to the latest and the ability to get valid Windows FILETIME values was broken

### CODE REVIEW

**Comment by NiKiZe** [comment]
Should the data be returned in an "handled" manner?
raw_data to me implies that it is raw bytearray data, and it is up to the caller to handle? (if this should be changed, so should all the other `ret = ` lines in the function as well)

`self.unpack_qword()` should probably be used instead.
```diff
-            ret = self._buf[data_offset + 4:data_offset + 4 + data_length]
+            ret = self.unpack_qword(data_offset + 4)
```

Could you elaborate on what "everything broke" means? maybe a stacktrace?
The woanware/usbdeviceforensics repo is empty on github? Otherwise i would have liked to see how this code is called.

IMHO The more correct solution would be this in `def data(self):`
```diff
-            return parse_windows_timestamp(d)
+            return parse_windows_timestamp(struct.unpack_from(str("<Q"), d, 0)[0])
```

If possible I would prefer a `git rebase` instead of the merge. (keeping repo history more clean)

**Comment by woanware** [comment]
Without the fix suggested then the values are not correctly parsed. I really don't mind how the fix is implemented, however, it was the last "cleanup" that didn't actually implement what the original code was attempting to do.

This was the original commit that added support for the RegFileTime:

https://github.com/williballenthin/python-registry/commit/1bfb035c784a915138f28437743bea8b1dc211fc

**Comment by NiKiZe** [comment]
I see, looks like a miss in the refacoring done in commit b6428982f15dc09b3dc6790deee4e0da1f18f7c6 (added comment)

For my reference (since I'm kind of a newbie to reg hives) could you point me to where the RegFileTime type can be found? (will for my own sake want to implement testcases for this in the future)

**Comment by woanware** [comment]
The RegFileTime type can be found is in a Win8 hive (which introduced lots of new data types). 

An example path is:

SYSTEM\CurrentControlSet\Enum\USBSTOR\Disk&Ven_Kingston&Prod_DataTraveler_G3&Rev_PMAP\000FEAFB9197BC7067D500C8&0\Properties\{83da6326-97a6-4088-9453-a1923f573b29}\0066\(Default)

More info on the data can be found here:

http://www.swiftforensics.com/2013/11/windows-8-new-registry-artifacts-part-1.html

The only reason I knew it was broken was that I had to implement the original code to parse the data out, as it wouldn't work that those particular keys, then investigation identified the new data type and parsing required.

**Comment by NiKiZe** [comment]
Thanks a bunch! Will look more on this in a few days, now that i know where I should be looking.

**Pull request closed without merging**
