### PR TITLE
Update RegTester

### PR DESCRIPTION
**Pull request by NiKiZe**
* To work with current code,
* Explained lines on non match in hive.
* Change reg parsing of MultiSZ

### CODE REVIEW

**Comment by NiKiZe** [comment]
PR as promised in #38
Will happily change anything that does not fit, and also do more testing if there is any historic examples of what needs to be tested.

**Comment by williballenthin** [comment]
This is great! The script had fallen out of use (for no good reason), but these fixes should encourage us to test more consistently.

**Comment by williballenthin** [comment]
Here's an idea I had been kicking around for a while that would obviate the need for much of this file...

developing a second backend to python-registry that operates over .reg files. So it exposes the familiar RegistryKey/RegistryValue interface, but the underlying data comes from a .reg export. This file format might be more accessible to those who can't immediately take a forensic image, or otherwise unlock hive files.

With this second backend, it would be trivial to do the testing comparison.

What do you think of this idea? Do you think it would be worth the effort of implementation?

**Comment by NiKiZe** [comment]
I agree a backend that supports .reg files instead of hives, but works in the same way on an interface level would be great. (if/when there is write support the export function mentioned in #4 should be using this as well).

For now however my priority is in reg dissection and minimal write support - or more correctly "build" or "export to hive" implementation. But the reg format would probably simplify this as well.

**Pull request merged**
